# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently. For technical reasons, this
# file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Skylight - Digital Government Consulting
email: hello@skylight.digital
description: >
  Skylight is a HUBZone digital consultancy driven
  by making government work in a digital world.

baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
url: https://skylight.digital
localhost: localhost:4000
twitter_url: https://twitter.com/skylight_hq
github_repo_url: https://github.com/skylight-hq
github_issues_url: https://github.com/skylight-hq/skylight.digital/issues
linkedin_url: ""
openco_url: ""
hackerone_url: https://hackerone.com/skylight_qgvpb
slack_invite_url: https://skylight-hq.slack.com/signup

twitter:
  username: skylight_hq
github:
  username: skylight-hq

analytics:
  google:
    code: 'UA-93543424-1' # change this to your Google analytics code

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

collections:
  service_areas:
    output: true
    permalink: /services/:path/
  projects:
    output: true
    permalink: /work/:path/

sass:
  style: compressed

include:
  - _service_areas
  - _projects
  - _policy_items

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - vendor
  - snippets

# Jekyll plugins
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
