# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently. For technical reasons, this
# file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Skylight - Digital Government Consulting
email: hello@skylight.digital
description: >
  Skylight is a HUBZone digital consultancy focused
  on making government work in a digital world.

baseurl: "" # the subpath of your site, e.g. /blog
permalink: title
url: https://skylight.digital
localhost: localhost:4000
twitter_url: ""
github_repo_url: ""
github_issues_url: https://github.com/skylight-digital/skylight.digital/issues
linkedin_url: ""
openco_url: ""

twitter:
  username: ""
github:
  username: skylight-digital

analytics:
  google:
    code: 'UA-93543424-1' # change this to your Google analytics code

# Build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - vendor
  - snippets

# Jekyll plugins
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemaps
