# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently. For technical reasons, this
# file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Skylight - Digital Government Consultancy
email: hello@skylight.digital
description: >
  Skylight is a HUBZone digital consultancy focused
  on making government work in a digital world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site (https://skylight.digital)
localhost: "localhost:4000"
twitter_username:
github_username: skylight-digital

# Build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
